import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Providers from '@/app/components/providers';
import { getServerSession } from 'next-auth';
import { cn } from '@sample/components/src/lib/utils';

const fontHeading = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-heading',
});

const fontBody = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-body',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();

  return (
    <html lang="ko" suppressHydrationWarning>
      <head />
      <body
        className={cn('antialiased', fontHeading.variable, fontBody.variable)}
      >
        <Providers session={session}>{children}</Providers>
      </body>
    </html>
  );
}
